import { PrismaClient, Role, ShirtSize } from "@prisma/client";
import bcrypt from "bcryptjs";
import { getGermanHolidays } from "../lib/german-holidays";

const prisma = new PrismaClient();

const GERMAN_STATES = [
  "Baden-Württemberg",
  "Bayern",
  "Berlin",
  "Brandenburg",
  "Bremen",
  "Hamburg",
  "Hessen",
  "Mecklenburg-Vorpommern",
  "Niedersachsen",
  "Nordrhein-Westfalen",
  "Rheinland-Pfalz",
  "Saarland",
  "Sachsen",
  "Sachsen-Anhalt",
  "Schleswig-Holstein",
  "Thüringen",
];

async function seedHolidays(adminId: string) {
  const currentYear = new Date().getFullYear();
  const years = [currentYear, currentYear + 1];
  let total = 0;

  for (const year of years) {
    const holidays = getGermanHolidays(year);

    for (const h of holidays) {
      const holiday = await prisma.holiday.upsert({
        where: { name_date: { name: h.name, date: h.date } },
        update: { states: h.states },
        create: {
          name: h.name,
          date: h.date,
          states: h.states,
          isAutoGenerated: true,
          createdById: adminId,
        },
      });

      // Auto-assign to relevant active users
      const users = await prisma.user.findMany({
        where:
          h.states.length === 0
            ? { isActive: true }
            : { isActive: true, state: { in: h.states } },
        select: { id: true },
      });

      for (const u of users) {
        await prisma.userHoliday.upsert({
          where: { userId_holidayId: { userId: u.id, holidayId: holiday.id } },
          update: {},
          create: { userId: u.id, holidayId: holiday.id, assignedById: null },
        });
      }

      total++;
    }

    console.log(`✅ Festivos ${year}: ${holidays.length} festivos sembrados`);
  }

  console.log(`✅ Total: ${total} festivos sembrados para ${years.join(" y ")}`);
}

async function main() {
  console.log("🌱 Iniciando seed...");

  // Create admin user
  const hashedPassword = await bcrypt.hash("Admin1234!", 12);

  const admin = await prisma.user.upsert({
    where: { email: "admin@umtelkomd.de" },
    update: {},
    create: {
      firstName: "Admin",
      lastName: "Umtelkomd",
      birthDate: new Date("1990-01-01"),
      email: "admin@umtelkomd.de",
      password: hashedPassword,
      phone: "+49 000 0000000",
      shirtSize: ShirtSize.L,
      pantsSize: "32x32",
      role: Role.ADMIN,
      state: "Berlin",
      mustChangePassword: true,
      isActive: true,
    },
  });

  console.log(`✅ Admin creado: ${admin.email}`);
  console.log(`📍 Estados disponibles: ${GERMAN_STATES.length} estados alemanes`);

  // Seed German holidays for last year, current year and next year
  console.log("🗓️  Sembrando festivos alemanes...");
  await seedHolidays(admin.id);

  console.log("✅ Seed completado exitosamente.");
  console.log("\n🔑 Credenciales iniciales:");
  console.log("   Email: admin@umtelkomd.de");
  console.log("   Password: Admin1234!");
  console.log("   ⚠️  Cambia la contraseña en el primer login.");
}

main()
  .catch((e) => {
    console.error("❌ Error en seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
