import { prisma } from "@/lib/prisma";
import { getGermanHolidays } from "./german-holidays";

/**
 * Auto-assigns a holiday to all relevant active users.
 *   states: []          → all active users (national)
 *   states: ["Bayern"]  → active users whose state is in the array
 *
 * Uses upsert, so calling this multiple times is safe (idempotent).
 */
export async function autoAssignHolidayToUsers(
  holidayId: string,
  states: string[]
): Promise<void> {
  const users = await prisma.user.findMany({
    where:
      states.length === 0
        ? { isActive: true }
        : { isActive: true, state: { in: states } },
    select: { id: true },
  });

  if (users.length === 0) return;

  await prisma.$transaction(
    users.map((u) =>
      prisma.userHoliday.upsert({
        where: { userId_holidayId: { userId: u.id, holidayId } },
        update: {},
        create: { userId: u.id, holidayId, assignedById: null },
      })
    )
  );
}

/**
 * Auto-assigns all relevant future holidays to a user.
 * Assigns national holidays + holidays that include the user's state.
 *
 * Used when a user is created or their state changes.
 * Only touches future (today onwards) holidays to avoid rewriting history.
 */
export async function autoAssignHolidaysToUser(
  userId: string,
  userState: string
): Promise<void> {
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  const holidays = await prisma.holiday.findMany({
    where: {
      date: { gte: today },
      OR: [
        { states: { isEmpty: true } },
        ...(userState ? [{ states: { has: userState } }] : []),
      ],
    },
    select: { id: true },
  });

  if (holidays.length === 0) return;

  await prisma.$transaction(
    holidays.map((h) =>
      prisma.userHoliday.upsert({
        where: { userId_holidayId: { userId, holidayId: h.id } },
        update: {},
        create: { userId, holidayId: h.id, assignedById: null },
      })
    )
  );
}

/**
 * Seeds holidays for a given year and auto-assigns them to all relevant users.
 * Uses upsert on (name, date) — idempotent, safe to run multiple times.
 *
 * Returns the number of holiday records upserted.
 */
export async function seedHolidaysForYear(
  year: number,
  createdById: string
): Promise<number> {
  const holidays = getGermanHolidays(year);

  for (const h of holidays) {
    const holiday = await prisma.holiday.upsert({
      where: { name_date: { name: h.name, date: h.date } },
      update: { states: h.states },
      create: {
        name: h.name,
        date: h.date,
        states: h.states,
        isAutoGenerated: true,
        createdById,
      },
    });

    await autoAssignHolidayToUsers(holiday.id, h.states);
  }

  return holidays.length;
}
